apiVersion: skaffold/v2beta10
kind: Config
metadata:
  name: python-helloworld
build:
  artifacts:
  - image: hello-python
    docker:
      dockerfile: Dockerfile
  local:
    push: false
deploy:
  kubectl:
    manifests:
    - /vagrant/manifests/app-deployment.yaml
